name: faraz_protfolio
description: Faraz Ahmad's Flutter portfolio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

# Flutter Assets
flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
# Flutter Assets End

# App Icon Settings
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png

  web:
    generate: true
    image_path: assets/images/app_icon.png
    background_color: "#0B1220"
    theme_color: "#087CFF"
# App Icon Settings End