// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARiGjp-rlMu15hhX8RvePmDLRC_EVS8Uo',
    appId: '1:249530960513:web:15e1cbb61753e2771d5b80',
    messagingSenderId: '249530960513',
    projectId: 'faraz-portfolio-730dd',
    authDomain: 'faraz-portfolio-730dd.firebaseapp.com',
    storageBucket: 'faraz-portfolio-730dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDav3EEcaaMlXpLN14msOvQW726h69YgIw',
    appId: '1:249530960513:android:2a2315beb445cad81d5b80',
    messagingSenderId: '249530960513',
    projectId: 'faraz-portfolio-730dd',
    storageBucket: 'faraz-portfolio-730dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJEhZBriQaCcrlscts7ymzRAkU5yJjoQ',
    appId: '1:249530960513:ios:8690889cb81d25b11d5b80',
    messagingSenderId: '249530960513',
    projectId: 'faraz-portfolio-730dd',
    storageBucket: 'faraz-portfolio-730dd.firebasestorage.app',
    iosBundleId: 'com.example.farazProtfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeJEhZBriQaCcrlscts7ymzRAkU5yJjoQ',
    appId: '1:249530960513:ios:8690889cb81d25b11d5b80',
    messagingSenderId: '249530960513',
    projectId: 'faraz-portfolio-730dd',
    storageBucket: 'faraz-portfolio-730dd.firebasestorage.app',
    iosBundleId: 'com.example.farazProtfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARiGjp-rlMu15hhX8RvePmDLRC_EVS8Uo',
    appId: '1:249530960513:web:eea9c2a5a376ed2a1d5b80',
    messagingSenderId: '249530960513',
    projectId: 'faraz-portfolio-730dd',
    authDomain: 'faraz-portfolio-730dd.firebaseapp.com',
    storageBucket: 'faraz-portfolio-730dd.firebasestorage.app',
  );
}
